export const actionTypes = {
  ME_CONNECTED: 'ME@CONNECTED',
  USER_SOMEBODY_CONNECTED: 'USER@SOMEBODY_CONNECTED',
  USER_SOMEBODY_DISCONNECTED: 'USER@SOMEBODY_DISCONNECTED',
  NOTE_CREATED: 'NOTE@CREATED',
  NOTE_UPDATED: 'NOTE@UPDATED',
  NOTE_DELETED: 'NOTE@DELETED',
}
